### ISSUE TITLE
Add proportion mediated 

### ISSUE THREAD

**Issue by cchoirat** [harvard-P01/causalMediation#10]

**Comment by cchoirat** [comment]
Implement associated delta method

**Comment by eggevdp** [comment]
Can we (re-)use the formulas for NIE and NDE already available in the code?

**Comment by eggevdp** [comment]
Linda:
"
Yes, I’d like the macro to output PM with standard error and confidence interval.
For the delta method we can save the standard errors of NIE and NDE that we previously compute and then the delta method is very easy to implement. delta method (~x1/(x1+x2), estmean, estsigma)
"
