### ISSUE TITLE
Implement delta method standard error

### ISSUE THREAD

**Issue by cchoirat** [harvard-P01/causalMediation#5]

**Comment by cchoirat** [comment]
General framework for delta method coded (function NIE_binbin_delta in file NIE.R).
- CDE done.
- Need to extend to the remaining cases in NIE.R and NDE.R.

@eggevdp could you please give it a try?

**Comment by eggevdp** [comment]
Hi Christine, sorry I was buried in other work. Will work on this ASAP.
